# Author: Lucien PIAT based on Sukanya Denni's work
# For: Project Pangenoak
# Date: January, 2025

configfile: ".config/masterconfig.yaml"
include: "scripts/parameter_retrieval.py"


import os
import yaml

container_registry = config.get("container_registry", "docker://registry.forgemia.inra.fr/asm4pg/genomasm4pg")
output_dir = config.get("output_dir", "results/")
     
rule all:
    input:
        # Required final assemblies and graphs
        expand(
            os.path.join(output_dir, "{sample}_results", "02_final_assembly", "hap{n}", "{sample}_final_hap{n}.fasta.gz"),
            sample=config["samples"].keys(), n=[1, 2]
        ),
        expand(
            os.path.join(output_dir, "{sample}_results", "02_final_assembly", "hap{n}", "cutoffs_graph_hap{n}.png"),
            sample=config["samples"].keys(), n=[1, 2]
        ),
        expand(
            os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "{sample}_hap{n}_genometools_stats.txt"),
            sample=config["samples"].keys(), n=[1, 2]
        ),
        expand(
            os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "busco", "short_summary.specific.{sample}_hap{n}.txt"),
            sample=config["samples"].keys(), n=[1, 2]
        ),
        expand(
            os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "{sample}_genometools_stats.txt"),
            sample=config["samples"].keys()
        )

# Genome assembly using hifiasm
rule hifiasm:
    input:
        reads = lambda wildcards: config["samples"][wildcards.sample]["fasta_gz"]
    output:
        hap1 = os.path.join(output_dir, "{sample}_results", "01_raw_assembly","{sample}.bp.hap1.p_ctg.gfa"),
        hap2 = os.path.join(output_dir, "{sample}_results", "01_raw_assembly","{sample}.bp.hap2.p_ctg.gfa")
    params:
        prefix = os.path.join(output_dir, "{sample}_results", "01_raw_assembly","{sample}"), 
        mode = get_mode, 
        run_1 = lambda wildcards: get_run(wildcards, run=1),
        run_2 = lambda wildcards: get_run(wildcards, run=2),
        purge_force = get_purge_force
    benchmark:
        os.path.join(output_dir, "{sample}_results", "01_raw_assembly", "{sample}_hifiasm_benchmark.txt")
    threads: 20
    resources:
        mem_mb=250000,
        time="80:00:00"
    container:
        f"{container_registry}/hifiasm:0.19.6"
    shell:
        """
        ./workflow/scripts/hifiasm_call.sh {params.mode} {params.purge_force} {threads} {input.reads} {params.run_1} {params.run_2} {params.prefix}
        """

# Convert the gfa files of hifiasm to fasta
TO_FA_CMD = r"""/^S/{print ">"$2;print $3}"""

rule pigz_gfa_to_fasta:
    input:
        hap1_gfa = rules.hifiasm.output.hap1,
        hap2_gfa = rules.hifiasm.output.hap2, 
        reads = lambda wildcards: config["samples"][wildcards.sample]["fasta_gz"]
    output:
        hap1 =  os.path.join(output_dir, "{sample}_results", "01_raw_assembly","{sample}_hap1.fasta.gz"),
        hap2 =  os.path.join(output_dir, "{sample}_results", "01_raw_assembly","{sample}_hap2.fasta.gz")
    threads: 4
    resources:
        mem_mb=25000,
        time="10:00:00"
    container:
        f"{container_registry}/pigz"
    shell:
        """
        awk {TO_FA_CMD:q} {input.hap1_gfa} | pigz -p {threads} > {output.hap1} &&
        awk {TO_FA_CMD:q} {input.hap2_gfa} | pigz -p {threads} > {output.hap2}
        """

# Potentialy purge the haplotigs using purge_dups
rule haplotigs_handling:
    input:
        hap_fasta = os.path.join(output_dir, "{sample}_results", "01_raw_assembly","{sample}_hap{n}.fasta.gz"),
        reads = lambda wildcards: config["samples"][wildcards.sample]["fasta_gz"]
    output:
        hap = os.path.join(output_dir, "{sample}_results", "02_final_assembly","hap{n}","{sample}_final_hap{n}.fasta.gz"),
        cutoffs = os.path.join(output_dir, "{sample}_results", "02_final_assembly","hap{n}","cutoffs")
    params:
        prefix = "{sample}_hap{n}",
        dirr = os.path.join(output_dir, "{sample}_results", "02_final_assembly", "hap{n}"),
        purge_dups_option = get_purge_bool
    threads: 20
    resources:
        mem_mb=100000,
        time="80:00:00"
    container:
        f"{container_registry}/purge_dups1.2.5"
    shell:
        """
        ./workflow/scripts/haplotigs_handling.sh {params.purge_dups_option} {input.hap_fasta} {output.hap} {params.prefix} {input.reads} {params.dirr}
        """

# Rule to unsip the haplotypes if needed for other rules
rule unpigz_to_fasta:
    input:
        rules.haplotigs_handling.output.hap
    output:
        temp(os.path.join(output_dir, "{sample}_results", "02_final_assembly","hap{n}","{sample}_final_hap{n}.fasta"))
    container:
        f"{container_registry}/pigz"
    threads: 4
    resources:
        mem_mb=25000,
        time="10:00:00"
    shell:
        "unpigz -k -p 1 {input}"


# Make purge_dups cutoffs graph
rule cutoffs_graph:
    input:
        rules.haplotigs_handling.output.cutoffs
    output:
        graph = os.path.join(output_dir, "{sample}_results", "02_final_assembly","hap{n}","cutoffs_graph_hap{n}.png")
    params:
        dirr = os.path.join(output_dir, "{sample}_results", "02_final_assembly", "hap{n}")
    threads: 1
    resources:
        mem_mb=10000,
        time="01:00:00"
    container:
        f"{container_registry}/matplotlib0.11.5"
    shell:
        "python3 workflow/scripts/hist_plot.py -c {input} {params.dirr}/PB.stat {output.graph}"

# Produce basic stats for the reads files
rule genometools_on_raw_data:
    input:
        lambda wildcards: config["samples"][wildcards.sample]["fasta_gz"]
    output:
        os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "{sample}_genometools_stats.txt")
    priority: 1
    resources:
        mem_mb=100000,
        time="10:00:00"
    threads: 4
    container:
        f"{container_registry}/genometools1.5.9"
    shell:
        "gt seqstat {input} > {output}"

# NOT TESTED
# Produce basic stats for each haplotypes assembled
use rule genometools_on_raw_data as genometools_on_assembly with:
    input:
        rules.haplotigs_handling.output.hap
    output:
        os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "{sample}_hap{n}_genometools_stats.txt")
    priority: 0

# NOT TESTED
# BUSCO stats on assembly (may not work on first run, rerun the WF)
rule busco:
    input:
        rules.unpigz_to_fasta.output
    output:
        os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "busco", "short_summary.specific.{sample}_hap{n}.txt")
    params:
        prefix = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "busco"),
        lineage=get_busco_lin, 
        sample="{sample}_hap{n}"
    threads: 20
    resources:
        mem_mb=100000,
        time="10:00:00"
    container:
        f"{container_registry}/busco:5.7.1"
    shell:
        "busco -f -i {input} -l {params.lineage} --out_path {params.prefix} -o {params.sample} -m genome -c {threads}"

# NOT TESTED
# Estimate telomeric region content
rule find_telomeres:
    input:
        rules.unpigz_to_fasta.output
    output:
        os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "telomeres", "{sample}_hap{n}_telomeres.txt")
    threads: 4
    resources:
        mem_mb=40000,
        time="10:00:00"
    container:
        f"{container_registry}/biopython1.75"
    shell:
        "python3 workflow/scripts/FindTelomeres.py {input} > {output}"

# NOT TESTED
# Count k-mers in the input reads and generate a histogram of k-mer frequencies.
rule jellyfish:
    input:
        reads = lambda wildcards: config["samples"][wildcards.sample]["fasta_gz"]
    output:
        jf = os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "jellyfish", "{sample}.jf"),
        histo = os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "jellyfish", "{sample}.histo")
    params:
        km_size = get_kmer_size
    threads: 10
    resources:
        mem_mb=8000,
        time="10:00:00"
    container:
        f"{container_registry}/jellyfish2.3.0"
    shell:
        """
        jellyfish count -m {params.km_size} -s 100M -t {threads} -o {output.jf} -C <(zcat {input.reads}) && 
        jellyfish histo -h 1000000 -t {threads} {output.jf} > {output.histo}
        """

# NOT TESTED
# Analyze the k-mer histogram and estimate genome characteristics, including genome size, heterozygosity, and error rates. 
rule genomescope:
    input:
        rules.jellyfish.output.histo
    output:
        plot = os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "genomescope", "linear_plot.png")
    params:
        ploidy = get_ploidy,
        km_size = get_kmer_size,
        dirr = os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "genomescope"),
    resources:
        mem_mb=40000,
        time="10:00:00"
    container:
        f"{container_registry}/genomescope2.0"
    shell:
        "genomescope.R -k {params.km_size} -i {input} -o {params.dirr} -p {params.ploidy}"

# NOT TESTED
# Compare the k-mer content between the assembly and the raw reads.
rule kat:
    input:
        hap = rules.haplotigs_handling.output.hap,
        jellyfish = rules.jellyfish.output.histo
    output:
        os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "katplot", "{sample}_hap{n}.katplot.png")
    params:
        dirr = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "katplot", "{sample}_hap{n}"),
        km_size = get_kmer_size
    threads: 4
    resources:
        mem_mb=40000,
        time="10:00:00"
    container: 
        f"{container_registry}/kat2.4.1"
    shell:
        """
        kat comp -o {params.dirr} -t {threads} -m {params.km_size}--output_type png -v {input.jellyfish} {input.hap} && 
        kat plot spectra-cn -x 200 -o {params.dirr}.katplot.png {params.path}-main.mx
        """

# NOT TESTED
# Creates a k-mer database from the input reads 
rule meryl:
    input:
        lambda wildcards: config["samples"][wildcards.sample]["fasta_gz"]
    output:
        os.path.join(output_dir, "{sample}_results", "03_raw_data_qc", "merqury", "{sample}_reads-db.meryl")
    params:
        km_size = get_kmer_size
    threads: 20
    resources:
        mem_mb=60000, 
        time="10:00:00"
    container:
        f"{container_registry}/merqury1.3"
    shell:
        "meryl k={params.km_size} threads={threads} count {input} output {output}"

# NOT TESTED
# Calculates metrics like QV and completeness, providing a quantitative assessment of the genome assembly.
rule merqury:
    input:
        km_database = rules.meryl.output,
        hap1 = os.path.join(output_dir, "{sample}_results", "02_final_assembly","hap1","{sample}_final_hap1.fasta.gz"),
        hap2 = os.path.join(output_dir, "{sample}_results", "02_final_assembly","hap2","{sample}_final_hap2.fasta.gz"),
    output:
        qv = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "merqury", "{sample}_merqury.qv"),
        stats = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "merqury", "{sample}_merqury.completeness.stats")
    params:
        prefix = "{sample}_merqury",
        dirr = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "merqury")
    threads: 20
    resources:
        mem_mb=60000, 
        time="10:00:00"
    container:
        f"{container_registry}/merqury1.3"
    shell:
        """
        # Create temporary copies of haplotypes
        cp {input.hap1} {params.dirr}/tmp_hap1.fasta.gz
        cp {input.hap2} {params.dirr}/tmp_hap2.fasta.gz

        # Run Merqury
        cd {params.dirr} && \
        export MERQURY=/usr/local/share/merqury && \
        merqury.sh {input.read_db} {params.dirr}/tmp_hap1.fasta.gz {params.dirr}/tmp_hap1.fasta.gz {params.prefix}
        """

# NOT TESTED
# Identifies LTR retrotransposons
rule LTR_finder:
    input:
        rules.unpigz_to_fasta.output
    output:
        os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "LTR", "{sample}_hap{n}.scn")
    resources:
        mem_mb=60000, 
        time="50:00:00"
    container:
        f"{container_registry}/ltr_finder:latest"
    shell:
        "ltr_finder -C {input} > {output}"

# NOT TESTED
# Calculates the LTR Assembly Index (LAI), a metric for assembly quality based on LTR retrotransposons
rule LTR_retriever:
    input:
        scn = rules.LTR_finder.output,
        hap = rules.unpigz_to_fasta.output
    output:
        lai = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "LTR", "{sample}_hap{n}.out.LAI"),
        recap =  os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "LTR", "recap_{sample}_hap{n}.tbl")
    params:
        prefix="{sample}_hap{n}",
        dirr = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap{n}", "LTR")
    threads: 20
    resources:
        mem_mb=250000, 
        time="50:00:00"
    container:
        f"{container_registry}/ltr_retriever:3.0.1"
    shell:
        '''
        export PATH="/opt/LTR_retriever:$PATH" && 
        cd {params.dirr} &&
        LTR_retriever -threads {threads} -genome {input.hap} -infinder {input.scn} && 
        mv {params.prefix}.fa.out.LAI {output.lai} && 
        mv {params.prefix}.fa.tbl {output.recap}  && 
        rm {params.prefix}.fa?* &&  
        rm -rf .RepeatMaskerCache &&
        rm {params.prefix}.fa
        '''

# Rule to generate the html report
rule generate_report:
    input:
        genomescope = rules.genomescope.output.plot,
        genometools_on_raw_data = rules.genometools_on_raw_data.output,

        genometools_hap1 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap1", "{sample}_hap1_genometools_stats.txt"),
        genometools_hap2 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap2", "{sample}_hap2_genometools_stats.txt"),
        
        busco_hap2 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap1", "busco", "short_summary.specific.{sample}_hap1.txt"),
        busco_hap1 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap2", "busco", "short_summary.specific.{sample}_hap2.txt"),

        kplot_hap1 =os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap1", "katplot", "{sample}_hap1.katplot.png"),
        kplot_hap2 =os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap2", "katplot", "{sample}_hap2.katplot.png"),

        telomeres_hap1 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap1", "telomeres", "{sample}_hap1_telomeres.txt"),
        telomeres_hap2 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap2", "telomeres", "{sample}_hap2_telomeres.txt"),
        
        LAI_hap1 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap1", "LTR", "{sample}_hap1.out.LAI"),
        LAI_hap2 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap2", "LTR", "{sample}_hap2.out.LAI"),
        
        LRT_recap_hap1 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap1", "LTR", "recap_{sample}_hap1.tbl"),
        LRT_recap_hap2 = os.path.join(output_dir, "{sample}_results", "04_assembly_qc", "hap2", "LTR", "recap_{sample}_hap2.tbl"),

        merqury_stats=rules.merqury.output.stats,
        merqury_qv=rules.merqury.output.qv
    output:
        os.path.join(output_dir, "{sample}_results", "{sample}_assembly_report.html")
    params:
        sample = "{sample}",
        mode = get_mode,
        assembly_purge_force = get_purge_force,
        run_purge_dups = get_purge_bool,
        busco_lineage = get_busco_lin,
        ploidy = get_ploidy,
        kmer_size = get_kmer_size,
        r1 = lambda wildcards: get_run(wildcards, run=1),
        r2 = lambda wildcards: get_run(wildcards, run=2)
    resources:
        mem_mb=10000, 
        time="10:00:00"
    container:
        f"{container_registry}/rmarkdown4.0.3"
    script:
        "../scripts/report.Rmd"

# Rule to relocate the report 
rule relocate_report:
    input:
        rules.generate_report.output
    output:
        os.path.join(output_dir, "{sample}_results", "{sample}_assembly_report.html"),
    shell:
        "mv {input} {output}"