configfile: ".config/masterconfig.yaml"

res_path=config["root"] + "/" + config["resdir"]

###### Include all scripts & rules necessary to run the workflow ######
### Scripts
# get parameters from masterconfig
include: "scripts/from_config/hifiasm_mode.py"
include: "scripts/from_config/parameters.py"
include: "scripts/from_config/target_list.py"

### Rules
## PRE ASSEMBLY QC
include: "rules/01_qc.smk"
## ASSEMBLY
include: "rules/02_asm.smk"
# Statistics
include: "rules/03_asm_qc.smk"
include: "rules/03.5_asm_qc_merqury.smk"
# Purging
include: "rules/04_purge_dups.smk"
include: "rules/05_purged_asm_qc.smk"
include: "rules/05.5_purged_asm_qc_merqury.smk"
# Link final assembly
include: "rules/06_sym_link_hap.smk"
## AUTOMATIC REPORT
include: "rules/07_report.smk"

## runtime
include: "rules/00_runtime.smk"

###### get filenames for workflow ######
IDS=config["IDS"]
bamIDS=check_bam(IDS)
fastqIDS=check_fastq(IDS)
####
RUNID = run_id(config["IDS"])
BID_RUN = run_BFid(bamIDS)
FID_RUN = run_BFid(fastqIDS)

###### results path ######
res_path=config["root"] + "/" + config["resdir"]

###### Target files ######
## raw data stats
longqc_output = expand(res_path + "/{Bid}/{run}/01_raw_data_QC/02_longQC", zip,
    run=BID_RUN, Bid=bamIDS),
fastqc_output =  expand(res_path + "/{Fid}/{run}/01_raw_data_QC/01_fastQC/{Fid}_fastqc.{ext}", zip,
    run=FID_RUN, Fid=fastqIDS, ext=["html", "zip"])

### REPORT
REP_ID = for_report(IDS)
RUNID_REG = run_id(REP_ID)
BUSCO_LIN = busco_lin(REP_ID)

report_output = expand(res_path + "/{runid}/report_{id}.{lin}.html", zip,
    runid=RUNID_REG, id=REP_ID, lin = BUSCO_LIN )

### REPORT TRIO
REP_TRIO_ID = for_report_trio(IDS)
RUNID_TRIO = run_id(REP_TRIO_ID)
BUSCO_LIN_TRIO = busco_lin(REP_TRIO_ID)


report_trio_output = expand(res_path + "/{runid}/report_trio_{id}.{lin}.html", zip,
    runid=RUNID_TRIO, id=REP_TRIO_ID, lin = BUSCO_LIN_TRIO)

### SYM LINK
## symbolic link to final assembly
symb_link1 = expand(res_path + "/{runid}/{id}_hap{n}.fa", zip,
    runid=RUNID_REG, id=REP_ID, n=["1", "2"])
symb_link2 = expand(res_path + "/{runid}/{id}_hap{n}.fa", zip,
    runid=RUNID_TRIO, id=REP_TRIO_ID, n=["1", "2"])

## PURGE_DUPS CUTOFFS GRAPH
cut_eval1 = expand(res_path + "/{runid}/02_genome_assembly/02_after_purge_dups_assembly/00_assembly/{id}_hap{n}/cutoffs_graph_hap{n}.png", zip,
    runid=RUNID_REG, id=REP_ID, n=["1", "2"])
cut_eval2 = expand(res_path + "/{runid}/02_genome_assembly/02_after_purge_dups_assembly/00_assembly/{id}_hap{n}/cutoffs_graph_hap{n}.png", zip,
    runid=RUNID_TRIO, id=REP_TRIO_ID, n=["1", "2"])

## BUSCO
busco_reg = expand(res_path + "/{runid}/02_genome_assembly/01_raw_assembly/01_assembly_QC/busco/{id}_hap{n}/short_summary.specific.{lin}.{id}_hap{n}.txt", zip,
    runid=RUNID_REG, id=REP_ID, n=["1", "2"], lin = BUSCO_LIN)
busco_purged_reg = expand(res_path + "/{runid}/02_genome_assembly/02_after_purge_dups_assembly/01_assembly_QC/busco/{id}_purged_hap{n}/short_summary.specific.{lin}.{id}_purged_hap{n}.txt", zip,
    runid=RUNID_REG, id=REP_ID, n=["1", "2"], lin = BUSCO_LIN)

busco_trio = expand(res_path + "/{runid}/02_genome_assembly/01_raw_assembly/01_assembly_QC/busco/{id}_hap{n}/short_summary.specific.{lin}.{id}_hap{n}.txt", zip,
    runid=RUNID_TRIO, id=REP_TRIO_ID, n=["1", "2"], lin = BUSCO_LIN_TRIO)
busco_purged_trio = expand(res_path + "/{runid}/02_genome_assembly/02_after_purge_dups_assembly/01_assembly_QC/busco/{id}_purged_hap{n}/short_summary.specific.{lin}.{id}_purged_hap{n}.txt", zip,
    runid=RUNID_TRIO, id=REP_TRIO_ID, n=["1", "2"], lin = BUSCO_LIN_TRIO)

## RUNTIME
time = expand(res_path + "/{runid}/runtime.{id}.{lin}.txt", zip,
    runid = RUNID_REG, id=REP_ID, lin=BUSCO_LIN)
time_trio = expand(res_path + "/{runid}/runtime_trio.{id}.{lin}.txt", zip,
    runid = RUNID_TRIO, id=REP_TRIO_ID, lin=BUSCO_LIN_TRIO)

rule_all_input_list = [
    longqc_output,
    fastqc_output,
    cut_eval1,
    cut_eval2,
    symb_link1,
    symb_link2,
    report_output,
    report_trio_output,
    busco_reg,
    busco_purged_reg,
    busco_trio,
    busco_purged_trio,
    time,
    time_trio
]

#### target files
rule all:
    input:
        all_input = rule_all_input_list