test_job:
  stage: test
  image: continuumio/miniconda3  
  script:
    - conda install -c conda-forge mamba  # Install Mamba
    - mamba create -n snakemake -c conda-forge -c bioconda snakemake  # Create environment and install Snakemake
    - echo "source activate snakemake" > ~/.bashrc  # Ensure the environment is activated
    - source activate snakemake
    - snakemake --version
    - cd GenomAsm4pg
    - touch test_data.fasta.gz
    - source activate snakemake 
    - echo "test over"