# requiring the environment of NodeJS LTS
image: node:lts

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

before_script:
  - npm init --yes
  - npm install honkit --save-dev

test:
  stage: test
  script:
    - npx honkit build . public # build to public path
  only:
    - branches # this job will affect every branch except 'main'
  except:
    - main
    
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - npx honkit build . public # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main # this job will affect only the 'main' branch
