#!/bin/bash
#SBATCH --cpus-per-task=5
#SBATCH -o slurm_logs/out_job_%j.out
#SBATCH -e slurm_logs/err_job_%j.err
#SBATCH --time=80:00:00
#SBATCH -J asm4pg
#SBATCH --mem=10G
#SBATCH --ntasks=1

# Written by Lucien Piat at INRAe
# Use this script to run asm4pg on a HPC

# Verify arguments
if [ $# -ne 1 ] || [ "$1" == "help" ]; then
    echo "Use this script to run asm4pg"
    echo ""
    echo "Usage: asm4pg [dry|run|local-run|dag|rulegraph|unlock]"
    echo "    dry - run in dry-run mode"
    echo "    run - run the workflow with SLURM"
    echo "    local-run - run the workflow localy (on a single node)"
    echo "    dag - generate the directed acyclic graph for the workflow"
    echo "    rulegraph - generate the rulegraph for the workflow"
    echo "    unlock - Unlock the directory if snakemake crashed"
    exit 1
fi
echo "Welcome to Asm4pg! Make sure .config/masterconfig.yaml is correctly edited for this run."

# Update this with the path to your images
echo 'Asm4pg -> Loading modules'
module purge
module load containers/Apptainer/1.2.5      #On Genotoul
module load devel/Miniconda/Miniconda3      #On Genotoul

#module load snakemake/7.8.5                #On CBIB

echo 'Asm4pg -> Activating environment'
source activate wf_env
#conda activate wf_env                      #On CBIB

echo 'Asm4pg -> Starting Snakemake workflow'

run_snakemake() {
    local option="$1"

    case "$option" in
        dry)
            snakemake -c $(nproc) --dry-run
            ;;
        dag)
            snakemake -c $(nproc) --dag > dag.dot 
            if [ $? -eq 0 ]; then
                echo "Asm4pg -> DAG has been successfully generated as dag.dot"
            else
                echo "Asm4pg -> Error: Failed to generate DAG."
                exit 1
            fi
            ;;
        rulegraph)
            snakemake -c $(nproc) --rulegraph > rulegraph.dot 
            if [ $? -eq 0 ]; then
                echo "Asm4pg -> Rulegraph has been successfully generated as rulegraph.dot"
            else
                echo "Asm4pg -> Error: Failed to generate Rulegraph."
                exit 1
            fi
            ;;
        unlock)
            snakemake -c $(nproc) --unlock 
            ;;
        run)
            snakemake --workflow-profile ./.config/snakemake/profiles/slurm --keep-incomplete
            ;;
        local-run)
            SNG_BIND=$(pwd)
            snakemake --use-singularity --singularity-args "-B $SNG_BIND" -j $(nproc)
            ;;
        *)
            echo "Invalid option: $option"
            echo "Usage: $0 [dry|run|local-run|dag|rulegraph|unlock]"
            exit 1
            ;;
    esac
}

# Execute the function with the provided option
run_snakemake "$1"
