# Config file

# Add the assembly runs you want to do under samples. 
# Here is an example of mininmal configuration. Refer to the documentation for all options

samples:
  mito:
    reads: test_genome.fasta.gz
    busco_lineage: mammalia_odb10
    reference_mitochondrial_genome: [human_mt.fasta, human_mt.gb]
    run_quast: True

# FULL path to your output dir (mandatory)
output_dir_pdw: /home/lucien/Documents/taches/15_mitohifi/GenomAsm4pg

# ----

# Container to pull the images from
container_registry: "docker://registry.forge.inrae.fr/asm4pg/genomasm4pg"
# You can modify the output path if you need to
output_dir: "results/"

# ----

# List of parameters :
#   fasta_gz: Your reads (mandatory)
#   mode: [default, hi-c, trio, ont] (default: default, use fasq or bam for ont)
#   r1: The run1/parent1 read file
#   r2: The run2/parent2 read file
#   run_purge_dups: [True, False] (default: False)
#   run_ragtag: [True, False] (default: False)
#   reference_genome: fasta.gz reference genome used for ragtag
#   reference_mitochondrial_genome: fasta file used to segregate mitochondrial contigs
#   busco_lineage: (default: eukaryota_odb10)
#   run_quast: [True, False] (default: False)

# Advanced parameters (we advise keeping default vaules)
#   assembly_purge_force: [1-3] (default: 3)
#   kmer_size: (default: 21)