# absolute path to your desired output path
root: /output/path

####################### optional prejob - data preparation #######################
# path to tar data
data: /path
# list of tar names
get_all_tar_filename: False
tarIDS: "tar_filename"

####################### job - workflow #######################
# number of threads used by pigz
pigz_threads: 4

### CONFIG



####################### workflow output directories #######################
# results directory
resdir: workflow_results

### PREJOB
# extracted input data
rawdir: 00_input_data
bamdir: 00_input_data/bam_files
fastxdir: 00_input_data/fastx_files

### JOB
# QC
qcdir: 01_raw_data_QC
fqc: 01_fastQC
lqc: 02_longQC
gentools: 03_genometools
kmer: 04_kmer

# assembly
assembdir: 02_genome_assembly
asm_raw: 01_raw_assembly
asm_purged: 02_after_purge_dups_assembly
asm_conta: 03_uncontaminated_assembly
asm: 00_assembly
asm_qc: 01_assembly_QC
