# Config file

# Add the assembly runs you want to do under samples. 
# Here is an example of mininmal configuration. Refer to the documentation for all options

samples:
  run2:
    fasta_gz: small_example.fasta.gz
    mode: default
    run_purge_dups: True
    assembly_purge_force: 2
    busco_lineage: eudicots_odb10
    reference_genome: small_ref.fasta.gz
    run_ragtag: True
#  run3:
#    fasta_gz: small_example.fasta.gz
#    mode: hi-c
#    r1: small_example.fasta.gz
#    r2: small_example.fasta.gz
#  run4:
#    fasta_gz: small_example.fasta.gz
#    mode: hi-c
#    r1: small_example.fasta.gz
#    r2: small_example.fasta.gz
#    run_ragtag: True
#    run_purge_dups: True
#    reference_genome: small_ref.fasta.gz
#  run1:
#    fasta_gz: small_example.fasta.gz
#    mode: default
#    run_purge_dups: False


# You can modify the output path if you need to
output_dir: "results/"
output_dir_pdw: /mnt/cbib/pangenoak_trials/GenomAsm4pg/

# This container registry will be used to download singularity images
container_registry: "docker://registry.forgemia.inra.fr/asm4pg/genomasm4pg"